apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
        - name: python
          image: 339712853459.dkr.ecr.us-east-1.amazonaws.com/ecr-foodieflow:latest
          ports:
            - containerPort: 80
          env:
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: configmap-python
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: configmap-python
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: configmap-python
                  key: DB_NAME
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: configmap-python
                  key: DB_HOST
            - name: COGNITO_POOL_ID
              valueFrom:
                configMapKeyRef:
                  name: configmap-python
                  key: COGNITO_POOL_ID
            - name: CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: configmap-python
                  key: CLIENT_ID
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8000
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8000
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 30
          resources:
            requests:
              cpu: 10m
 #     volumes:
 #       - name: aws-secrets
 #         csi:
 #           driver: secrets-store.csi.k8s.io
 #           readOnly: true
 #           volumeAttributes:
 #             secretProviderClass: "aws-secrets-provider"